# Optimized Netlify Configuration

[build]
  # Command to build the project
  command = "npm run build"
  # Directory to publish
  publish = "build"
  # Directory for serverless functions
  functions = "netlify/functions"

# Production context settings
[context.production]
  # Production-specific build command (optional, if different)
  command = "npm run build"
  # Production-specific publish directory (optional, if different)
  publish = "build"
  # Production-specific functions directory (optional, if different)
  functions = "netlify/functions"

  [context.production.environment]
    NODE_VERSION = "18"
    NODE_ENV = "production"
    GENERATE_SOURCEMAP = "false"

# Asset optimization
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.images]
  compress = true
  quality = 80 # Explicitly set image quality

# Custom headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    # Cache-Control for assets
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"

# Redirects and rewrites
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
