# Netlify Build Settings
[build]
  # This is the command to build your React app
  command = "npm run build"
  # This is the directory where your built files are located
  publish = "build"
  # Netlify Functions directory
  functions = "netlify/functions"

# Production environment settings
[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  # Disable source maps for smaller production builds
  GENERATE_SOURCEMAP = "false"

# Netlify's automatic asset optimization
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.images]
  compress = true

# Custom headers for improved security
[[headers]]
  for = "/*"
  [headers.values]
    # Prevent clickjacking
    X-Frame-Options = "DENY"
    # Prevent MIME-sniffing
    X-Content-Type-Options = "nosniff"
    # Control referrer information
    Referrer-Policy = "no-referrer"
    # Basic Content Security Policy
    Content-Security-Policy = "frame-ancestors 'none'"
    # Permissions policy
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
